//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-06-23(StabilimentoBalneare)
//  @ File Name : AffittoLettino.java
//  @ Date : 23/06/2010
//  @ Author : michrag
//
//

package dominio;

public class AffittoLettino
{
    static final int prezzo = 10;
    private Cliente cliente;
    private Periodo periodo;
    private int numLettini;

    public AffittoLettino(Cliente cliente, Periodo periodo, int numLettini)
    {
        super();
        this.cliente = cliente;
        this.periodo = periodo;
        this.numLettini = numLettini;
    }

    public Cliente getCliente()
    {
        return cliente;
    }

    public Periodo getPeriodo()
    {
        return periodo;
    }

    public int getNumLettini()
    {
        return numLettini;
    }

    public static int getPrezzo()
    {
        return prezzo;
    }

}
