//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-06-23(StabilimentoBalneare)
//  @ File Name : Cabina.java
//  @ Date : 23/06/2010
//  @ Author : michrag
//
//

package dominio;

public class Cabina
{
    private int numero;
    static final int prezzo1g = 30;
    static final int prezzo23gg = 30;
    static final int prezzo410gg = 25;
    static final int prezzo11gg = 23;
    private Occupazione occupazione;

    public Cabina(int numero)
    {
        super();
        this.numero = numero;
    }

    public Occupazione getOccupazione()
    {
        if(occupazione != null)
        {
            return occupazione;
        }

        throw new RuntimeException("Occupazione Inesistente");
    }

    public void setOccupazione(Occupazione occupazione)
    {
        this.occupazione = occupazione;
    }

    public int getNumero()
    {
        return numero;
    }

    public static int getPrezzo1g()
    {
        return prezzo1g;
    }

    public static int getPrezzo23gg()
    {
        return prezzo23gg;
    }

    public static int getPrezzo410gg()
    {
        return prezzo410gg;
    }

    public static int getPrezzo11gg()
    {
        return prezzo11gg;
    }



}
