//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-06-23(StabilimentoBalneare)
//  @ File Name : Cliente.java
//  @ Date : 23/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;

public class Cliente
{
    private String nome;
    private List<Periodo> periodi;
    private AffittoLettino affittoLettino;

    public Cliente(String nome)
    {
        super();
        this.nome = nome;
        periodi = new ArrayList<Periodo>();
    }

    public String getNome()
    {
        return nome;
    }

    public void addPeriodo(Periodo p)
    {
        periodi.add(p);
    }

    public List<Periodo> getPeriodi()
    {
        return periodi;
    }

    public AffittoLettino getAffittoLettino()
    {
        if(affittoLettino != null)
        {
            return affittoLettino;
        }

        throw new RuntimeException("AffittoLettino inesistente");
    }

    public void setAffittoLettino(AffittoLettino affittoLettino)
    {
        this.affittoLettino = affittoLettino;
    }


}
