//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-06-23(StabilimentoBalneare)
//  @ File Name : Occupazione.java
//  @ Date : 23/06/2010
//  @ Author : michrag
//
//

package dominio;

public class Occupazione
{
    private Ombrellone ombrellone = null;
    private Periodo periodo;
    private Cabina cabina = null;

    public Occupazione(Periodo periodo)
    {
        super();
        this.periodo = periodo;
    }

    public Cabina getCabina()
    {
        if(cabina != null)
        {
            return cabina;
        }

        throw new RuntimeException("Occupazione senza cabina");
    }

    public void setCabina(Cabina cabina)
    {
        this.cabina = cabina;
    }

    public Ombrellone getOmbrellone()
    {
        if(ombrellone != null)
        {
            return ombrellone;
        }

        throw new RuntimeException("Occupazione senza ombrellone");

    }

    public void setOmbrellone(Ombrellone ombrellone)
    {
        this.ombrellone = ombrellone;
    }

    public Periodo getPeriodo()
    {
        return periodo;
    }


}
