//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-06-23(StabilimentoBalneare)
//  @ File Name : Ombrellone.java
//  @ Date : 23/06/2010
//  @ Author : michrag
//
//

package dominio;

public class Ombrellone
{
    private String posizione;
    static final int prezzo1g = 25;
    static final int prezzo23gg = 20;
    static final int prezzo410gg = 19;
    static final int prezzo11gg = 17;
    private Occupazione occupazione = null;
    private Opzione opzione = null;


    public Ombrellone(String posizione)
    {
        super();
        this.posizione = posizione;
    }

    public String getPosizione()
    {
        return posizione;
    }

    public Occupazione getOccupazione()
    {
        if(occupazione != null)
        {
            return occupazione;
        }

        throw new RuntimeException("Occupazione inesistente");
    }

    public void setOccupazione(Occupazione occupazione)
    {
        this.occupazione = occupazione;
    }

    public Opzione getOpzione()
    {
        if(opzione != null)
        {
            return opzione;
        }

        throw new RuntimeException("Opzione inesistente");
    }

    public void setOpzione(Opzione opzione)
    {
        this.opzione = opzione;
    }

    public static int getPrezzo1g()
    {
        return prezzo1g;
    }

    public static int getPrezzo23gg()
    {
        return prezzo23gg;
    }

    public static int getPrezzo410gg()
    {
        return prezzo410gg;
    }

    public static int getPrezzo11gg()
    {
        return prezzo11gg;
    }



}
