//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-06-23(StabilimentoBalneare)
//  @ File Name : Opzione.java
//  @ Date : 23/06/2010
//  @ Author : michrag
//
//

package dominio;

public class Opzione
{
    private Ombrellone ombrellone;
    private Periodo periodo;

    public Opzione(Periodo periodo)
    {
        super();
        this.periodo = periodo;
    }


    public void setOmbrellone(Ombrellone ombrellone)
    {
        this.ombrellone = ombrellone;
    }

    public Ombrellone getOmbrellone()
    {
        return ombrellone;
    }

    public Periodo getPeriodo()
    {
        return periodo;
    }

}
