//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-06-23(StabilimentoBalneare)
//  @ File Name : Periodo.java
//  @ Date : 23/06/2010
//  @ Author : michrag
//
//

package dominio;

public class Periodo
{
    private int dataInizio;
    private int dataFine;
    private Cliente cliente;
    private Opzione opzione = null;
    private Occupazione occupazione = null;

    public Periodo(int dataInizio, int dataFine, Cliente cliente)
    {
        super();
        this.dataInizio = dataInizio;
        this.dataFine = dataFine;
        this.cliente = cliente;
    }

    public Opzione getOpzione()
    {
        if(opzione != null)
        {
            return opzione;
        }

        throw new RuntimeException("Opzione inesistente");
    }

    public void setOpzione(Opzione opzione)
    {
        this.opzione = opzione;
    }

    public Occupazione getOccupazione()
    {
        if(occupazione != null)
        {
            return occupazione;
        }

        throw new RuntimeException("Occupazione inesistente");
    }

    public void setOccupazione(Occupazione occupazione)
    {
        this.occupazione = occupazione;
    }

    public Cliente getCliente()
    {
        return cliente;
    }

    public int getDataInizio()
    {
        return dataInizio;
    }

    public int getDataFine()
    {
        return dataFine;
    }


}
