//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Carrozza.java
//  @ Date : 17/06/2010
//  @ Author : michrag
//
//

package dominio;
import java.util.*;

public class Carrozza
{
    public Treno treno;
    private boolean primaClasse;
    private boolean prenotabile;
    private int numero;
    private List<Posto> posti;


    public Carrozza(Treno treno, boolean primaClasse, boolean prenotabile,
                    int numero)
    {
        super();
        this.treno = treno;
        this.primaClasse = primaClasse;
        this.prenotabile = prenotabile;
        this.numero = numero;
        posti = new ArrayList<Posto>();
    }

    public boolean isPrimaClasse()
    {
        return primaClasse;
    }

    public boolean isPrenotabile()
    {
        return prenotabile;
    }
    public int getNumero()
    {
        return numero;
    }

    public List<Posto> getPosti()
    {
        return posti;
    }

    public void addPosto(Posto p)
    {
        posti.add(p);
    }


}
