//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Fermata.java
//  @ Date : 17/06/2010
//  @ Author : michrag
//
//


package dominio;

import java.util.*;

public class Fermata
{
    private int oraArrivo;
    private int oraPartenza;
    private Stazione stazione;
    boolean partenza = false;
    boolean intermedia = false;
    boolean arrivo = false;
    private List<Treno> treni;

    // costruttore per fermata di partenza o di arrivo
    public Fermata(int ora, boolean partenza, Stazione stazione)
    {
        super();

        if(partenza)
        {
            oraPartenza = ora;
            this.partenza = partenza;
        }

        if(!partenza)
        {
            oraArrivo = ora;
            arrivo = true;
        }

        this.stazione = stazione;
        treni = new ArrayList<Treno>();
    }

    // costruttore per fermata intermedia
    public Fermata(int oraArrivo, int oraPartenza, Stazione stazione)
    {
        super();
        this.oraArrivo = oraArrivo;
        this.oraPartenza = oraPartenza;
        this.stazione = stazione;
        intermedia = true;
        treni = new ArrayList<Treno>();
    }


    public int getOraArrivo()
    {
        return oraArrivo;
    }

    public int getOraPartenza()
    {
        return oraPartenza;
    }

    public Stazione getStazione()
    {
        return stazione;
    }

    public boolean isPartenza()
    {
        return partenza;
    }

    public boolean isIntermedia()
    {
        return intermedia;
    }

    public boolean isArrivo()
    {
        return arrivo;
    }

    public void addTreno(Treno t)
    {
        treni.add(t);
    }


}
