//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Posto.java
//  @ Date : 17/06/2010
//  @ Author : michrag
//
//
package dominio;

import java.util.*;


public class Posto
{
    private int numero;
    private List<Occupazione> occupazioni;



    public Posto(int numero)
    {
        super();
        this.numero = numero;
        occupazioni = new ArrayList<Occupazione>();
    }

    public int getNumero()
    {
        return numero;
    }

    public List<Occupazione> getOccupazioni()
    {
        return occupazioni;
    }

    public void addOccupazione(Occupazione o)
    {
        occupazioni.add(o);
    }

    public void rimuoviPrimaOccupazione()
    {
        occupazioni.remove(0);
    }

    public Occupazione getPrimaOccupazione()
    {
        return(occupazioni.get(0));

    }


}
