//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Stazione.java
//  @ Date : 17/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;


public class Stazione
{
    private String nome;
    private List<Fermata> fermate;

    public Stazione(String nome)
    {
        super();
        this.nome = nome;
        fermate = new ArrayList<Fermata>();
    }

    public String getNome()
    {
        return nome;
    }

    public void addFermata(Fermata f)
    {
        fermate.add(f);
    }

}
