//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tratta.java
//  @ Date : 17/06/2010
//  @ Author : michrag
//
//
package dominio;
import java.util.*;

public class Tratta
{
    private String numVerso;
    private List<Stazione> stazioni;
    private List<Treno> treni;

    public Tratta(String numVerso)
    {
        super();
        this.numVerso = numVerso;
        stazioni = new ArrayList<Stazione>();
        treni = new ArrayList<Treno>();
    }


    public String getNumVerso()
    {
        return numVerso;
    }

    public void addStazione(Stazione s)
    {
        stazioni.add(s);
    }

    public List<Stazione> getStazioni()
    {
        return stazioni;
    }

    public List<Treno> getTreni()
    {
        return treni;
    }

    public void addTreno(Treno t)
    {
        treni.add(t);
    }



}
