//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ES.java
//  @ Date : 17/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;


public class Treno
{
    private boolean es;
    private String id;
    private Tratta tratta;
    private List<Carrozza> carrozze;
    private List<Fermata> fermate;

    public Treno(String id, boolean eurostar)
    {
        super();
        this.id = id;
        es = eurostar;
        carrozze = new ArrayList<Carrozza>();
        fermate = new ArrayList<Fermata>();
    }

    public Tratta getTratta()
    {
        return tratta;
    }

    public void setTratta(Tratta tratta)
    {
        this.tratta = tratta;
    }

    public List<Carrozza> getCarrozze()
    {
        return carrozze;
    }

    public void addCarrozza(Carrozza c)
    {
        carrozze.add(c);
    }

    public List<Fermata> getFermate()
    {
        return fermate;
    }

    public void addFermata(Fermata f)
    {
        fermate.add(f);
    }

    public String getId()
    {
        return id;
    }

    public boolean isEurostar()
    {
        return es;
    }


}
