//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-04-21(Condominii)
//  @ File Name : AnnoFiscale.java
//  @ Date : 19/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;


public class AnnoFiscale
{
    private int anno;
    private List<Spesa> spese;

    public AnnoFiscale(int anno)
    {
        super();
        this.anno = anno;
        spese = new ArrayList<Spesa>();
    }

    public int getAnno()
    {
        return anno;
    }

    public void addSpesa(Spesa s)
    {
        spese.add(s);
    }

    public List<Spesa> getSpese()
    {
        return spese;
    }

}
