//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-04-21(Condominii)
//  @ File Name : Appartamento.java
//  @ Date : 19/06/2010
//  @ Author : michrag
//
//

package dominio;

public class Appartamento
{
    private int numInPiano;
    private int quota;
    private Piano piano;
    private Proprietario proprietario;

    public Appartamento(int numInPiano, int quota, Piano piano,
                        Proprietario proprietario)
    {
        super();
        this.numInPiano = numInPiano;
        this.quota = quota;
        this.piano = piano;
        this.proprietario = proprietario;
    }

    public int getNumInPiano()
    {
        return numInPiano;
    }

    public int getQuota()
    {
        return quota;
    }

    public Piano getPiano()
    {
        return piano;
    }

    public Proprietario getProprietario()
    {
        return proprietario;
    }

}
