//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-04-21(Condominii)
//  @ File Name : Condominio.java
//  @ Date : 19/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;

public class Condominio
{
    private String nome;
    private String indirizzo;
    private List<Edificio> edifici;

    public Condominio(String nome, String indirizzo)
    {
        super();
        this.nome = nome;
        this.indirizzo = indirizzo;
        edifici = new ArrayList<Edificio>();
    }

    public String getNome()
    {
        return nome;
    }

    public String getIndirizzo()
    {
        return indirizzo;
    }

    public void addEdificio(Edificio e)
    {
        edifici.add(e);
    }

    public Edificio getEdificio(int numEdificio)
    {
        for(Iterator<Edificio> i = edifici.iterator(); i.hasNext();)
        {
            Edificio edificio = (Edificio)i.next();

            if(edificio.getNumInCond() == numEdificio)
            {
                return edificio;
            }
        }

        throw new RuntimeException("Edificio inesistente.");
    }

    public List<Edificio> getEdifici()
    {
        return edifici;
    }

}
