//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-04-21(Condominii)
//  @ File Name : DiCondominio.java
//  @ Date : 19/06/2010
//  @ Author : michrag
//
//

package dominio;

public class DiCondominio extends Spesa
{

    private Condominio condominio;

    public DiCondominio(AnnoFiscale annoFiscale, int data, double importo,
                        String descrizione, Condominio condominio)
    {
        super(annoFiscale, data, importo, descrizione);
        this.condominio = condominio;
    }

    public Condominio getCondominio()
    {
        return condominio;
    }

    @Override
    public double calcolaQuotaParte(Appartamento a)
    {
        double quotaParte;

        quotaParte = ((importo * a.getQuota()) / 1000);

        return quotaParte;
    }

    @Override
    public void stampa()
    {
        System.out.println("\nSpesa di condominio");
        System.out.println("Condominio - Descrizione - Importo - Data");
        System.out.println(condominio.getNome() + " - " + descrizione + " - " + importo + " - " + data);

    }

    @Override
    public Edificio getEdificio()
    {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public Appartamento getAppartamento()
    {
        // TODO Auto-generated method stub
        return null;
    }

}
