//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-04-21(Condominii)
//  @ File Name : DiEdificio.java
//  @ Date : 19/06/2010
//  @ Author : michrag
//
//


package dominio;

import java.util.*;

public class DiEdificio extends Spesa
{

    private Edificio edificio;

    public DiEdificio(AnnoFiscale annoFiscale, int data, double importo,
                      String descrizione, Edificio edificio)
    {
        super(annoFiscale, data, importo, descrizione);
        this.edificio = edificio;
    }

    public Edificio getEdificio()
    {
        return edificio;
    }

    @Override
    public double calcolaQuotaParte(Appartamento a)
    {
        double quotaParte;
        double quotaMillesimale = a.getQuota();
        double somma = 0;

        List<Piano> piani = a.getPiano().getEdificio().getPiani();

        for(Iterator<Piano> i = piani.iterator(); i.hasNext();)
        {
            Piano piano = (Piano)i.next();
            List<Appartamento> appartamenti = piano.getAppartamenti();

            for(Iterator<Appartamento> j = appartamenti.iterator(); j.hasNext();)
            {
                Appartamento appartamento = (Appartamento)j.next();
                somma += appartamento.getQuota();
            }
        }

        quotaParte = ((importo * quotaMillesimale) / somma);

        return quotaParte;
    }

    @Override
    public void stampa()
    {
        System.out.println("\nSpesa di edificio");
        System.out.println("Condominio - Edificio (numero) - Descrizione - Importo - Data");
        System.out.println(edificio.getCondominio().getNome() + " - " + edificio.getNumInCond() + " - " + descrizione + " - " + importo + " - " + data);

    }

    @Override
    public Condominio getCondominio()
    {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public Appartamento getAppartamento()
    {
        // TODO Auto-generated method stub
        return null;
    }

}
