//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-04-21(Condominii)
//  @ File Name : Edificio.java
//  @ Date : 19/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;

public class Edificio
{
    private String indirizzo;
    private int numInCond;
    private Condominio condominio;
    private List<Piano> piani;

    public Edificio(String indirizzo, int numInCond, Condominio condominio)
    {
        super();
        this.indirizzo = indirizzo;
        this.numInCond = numInCond;
        this.condominio = condominio;
        piani = new ArrayList<Piano>();
    }

    public String getIndirizzo()
    {
        return indirizzo;
    }

    public int getNumInCond()
    {
        return numInCond;
    }

    public Condominio getCondominio()
    {
        return condominio;
    }

    public void addPiano(Piano p)
    {
        piani.add(p);
    }

    public Piano getPiano(int numPiano)
    {
        for(Iterator<Piano> i = piani.iterator(); i.hasNext();)
        {
            Piano piano = (Piano)i.next();

            if(piano.getNumeroInEd() == numPiano)
            {
                return piano;
            }
        }

        throw new RuntimeException("Piano inesistente.");
    }

    public List<Piano> getPiani()
    {
        return piani;
    }



}
