//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-04-21(Condominii)
//  @ File Name : Piano.java
//  @ Date : 19/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;


public class Piano
{
    private int numeroInEd;
    private Edificio edificio;
    private List<Appartamento> appartamenti;

    public Piano(int numeroInEd, Edificio edificio)
    {
        super();
        this.numeroInEd = numeroInEd;
        this.edificio = edificio;
        appartamenti = new ArrayList<Appartamento>();
    }

    public int getNumeroInEd()
    {
        return numeroInEd;
    }

    public Edificio getEdificio()
    {
        return edificio;
    }

    public void addAppartamento(Appartamento a)
    {
        appartamenti.add(a);
    }

    public List<Appartamento> getAppartamenti()
    {
        return appartamenti;
    }

}
