//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-04-21(Condominii)
//  @ File Name : Proprietario.java
//  @ Date : 19/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;


public class Proprietario
{
    private String nome;
    private List<Appartamento> appartamenti;

    public Proprietario(String nome)
    {
        super();
        this.nome = nome;
        appartamenti = new ArrayList<Appartamento>();
    }

    public String getNome()
    {
        return nome;
    }

    public void addAppartamento(Appartamento a)
    {
        appartamenti.add(a);
    }

    public List<Appartamento> getAppartamenti()
    {
        return appartamenti;
    }

}
