//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 2010-04-21(Condominii)
//  @ File Name : Spesa.java
//  @ Date : 19/06/2010
//  @ Author : michrag
//
//


package dominio;

public abstract class Spesa
{
    protected AnnoFiscale annoFiscale;
    protected int data;
    protected double importo; // importo TOTALE della spesa
    protected String descrizione;

    public Spesa(AnnoFiscale annoFiscale, int data, double importo,
                 String descrizione)
    {
        super();
        this.annoFiscale = annoFiscale;
        this.data = data;
        this.importo = importo;
        this.descrizione = descrizione;
    }

    public AnnoFiscale getAnnoFiscale()
    {
        return annoFiscale;
    }

    public int getData()
    {
        return data;
    }

    public double getImporto()
    {
        return importo;
    }

    public String getDescrizione()
    {
        return descrizione;
    }

    public abstract double calcolaQuotaParte(Appartamento a); // calcola la frazione di spesa imputabile all'appartamento che invoca questo metodo
    public abstract void stampa();
    public abstract Condominio getCondominio();
    public abstract Edificio getEdificio();
    public abstract Appartamento getAppartamento();
}
