//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Albergo.java
//  @ Date : 15/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;

public class Albergo
{


    private List<Camera> camere;
    private List<Cliente> clienti;
    private List<Soggiorno> soggiorni;

    // pattern Singleton
    private static Albergo instance = null;

    private Albergo()
    {
        camere = new ArrayList<Camera>();
        clienti = new ArrayList<Cliente>();
        soggiorni = new ArrayList<Soggiorno>();
    }

    public static Albergo getInstance()
    {
        if(instance == null)
        {
            instance = new Albergo();
        }

        return instance;
    } // fine pattern Singleton


    // metodi per camere
    public void addCamera(Camera camera)
    {
        camere.add(camera);
    }

    public Camera getCamera(String nome)
    {
        for(Iterator<Camera> i = camere.iterator(); i.hasNext();)
        {
            Camera camera = (Camera)i.next();

            if(camera.getNome().equalsIgnoreCase(nome))
            {
                return camera;
            }
        }

        throw new RuntimeException("Camera non presente.");
    }

    public List<Camera> getCamere()
    {
        return camere;
    }

    // metodi per clienti
    public void addCliente(Cliente cliente)
    {
        clienti.add(cliente);
    }

    public Cliente getCliente(String nome)
    {
        for(Iterator<Cliente> i = clienti.iterator(); i.hasNext();)
        {
            Cliente cliente = (Cliente)i.next();

            if(cliente.getNome().equalsIgnoreCase(nome))
            {
                return cliente;
            }
        }

        throw new RuntimeException("Cliente inesistente.");
    }


    // metodi per soggiorni
    public void addSoggiorno(Soggiorno soggiorno)
    {
        soggiorni.add(soggiorno);
    }

    public List<Soggiorno> getSoggiorni()
    {
        return soggiorni;
    }

    public void rimuoviSoggiorno(Soggiorno s)
    {
        soggiorni.remove(s);
    }

}
