//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Camera.java
//  @ Date : 15/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;

public class Camera
{
    private String nome;
    private boolean occupata;
    private double prezzo;
    private boolean prenotata;
    private int posti;
    private List<Soggiorno> soggiorni;

    public Camera(String nome, int posti, double prezzo)
    {
        super();
        this.nome = nome;
        this.posti = posti;
        this.prezzo = prezzo;
        occupata = false;
        prenotata = false;
        soggiorni = new ArrayList<Soggiorno>();
    }

    public String getNome()
    {
        return nome;
    }

    public int getPosti()
    {
        return posti;
    }

    public void addSoggiorno(Soggiorno soggiorno)
    {
        soggiorni.add(soggiorno);
    }

    public List<Soggiorno> getSoggiorni()
    {
        return soggiorni;
    }

    public void setPrenotata(boolean val)
    {
        prenotata = val;
    }

    public double getPrezzo()
    {
        return prezzo;
    }

    public boolean isPrenotata()
    {
        return prenotata;
    }

    public boolean isOccupata()
    {
        return occupata;
    }

    public void setOccupata(boolean val)
    {
        occupata = val;
    }
}
