//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 15/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;

public class Cliente
{
    private String nome;
    private int numCdC;
    private Soggiorno soggiorno;
    private String tipo;

    public Cliente(String nome)
    {
        super();
        this.nome = nome;
        tipo = "potenziale";
    }

    public String getNome()
    {
        return nome;
    }

    // metodi per tipo
    public void setTipo(String tipo)
    {
        this.tipo = tipo;
    }

    public String getTipo()
    {
        return tipo;
    }

    // metodi per soggiorno
    public void setSoggiorno(Soggiorno soggiorno)
    {
        this.soggiorno = soggiorno;
    }

    public Soggiorno getSoggiorno()
    {
        return soggiorno;
    }

    // metodi per CdC
    public void setCdC(int num)
    {
        numCdC = num;
    }

}
