//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ContoFinale.java
//  @ Date : 15/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;

public class ContoFinale
{
    private double importo;
    private boolean contanti = false;
    private boolean assegno = false;
    private boolean CdC = false;
    private boolean pagato = false;
    private List<Spesa> spese;

    public ContoFinale(String pag)
    {
        if(pag.equalsIgnoreCase("contanti"))
        {
            contanti = true;
        }

        if(pag.equalsIgnoreCase("assegno"))
        {
            assegno = true;
        }

        if(pag.equalsIgnoreCase("cdc"))
        {
            CdC = true;
        }

        spese = new ArrayList<Spesa>();

        pagato = true;

    }

    public void setImporto(double imp)
    {
        importo = imp;
    }

    public void addSpesa(Spesa s)
    {
        spese.add(s);
    }
}
