//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Prenotazione.java
//  @ Date : 15/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;




public class Prenotazione
{
    private int data;
    private int dataCanc;
    public Soggiorno soggiorno;

    public Prenotazione(int data, Soggiorno soggiorno)
    {
        this.data = data;
        this.soggiorno = soggiorno;
    }

    public void setDataCanc(int num)
    {
        dataCanc = num;
    }

    public Soggiorno getSoggiorno()
    {
        return soggiorno;
    }
}
