//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Soggiorno.java
//  @ Date : 15/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;

public class Soggiorno
{
    private int dataInizio;
    private int dataFine;
    private boolean inCorso;
    private List<Spesa> spese;
    private Prenotazione prenot;
    private Camera camera;
    private ContoFinale conto;
    private List<Cliente> clienti;

    public Soggiorno(int dataInizio, int dataFine, Camera camera, Cliente cliente)
    {
        this.dataInizio = dataInizio;
        this.dataFine = dataFine;
        this.camera = camera;
        clienti = new ArrayList<Cliente>();
        clienti.add(cliente);
        inCorso = false;
        spese = new ArrayList<Spesa>();
    }

    public Prenotazione getPrenot()
    {
        return prenot;
    }

    public void setPrenot(Prenotazione p)
    {
        prenot = p;
    }

    public void setInCorso(boolean val)
    {
        inCorso = val;
    }

    public void addSpesa(Spesa spesa)
    {
        spese.add(spesa);
    }

    public int getDataInizio()
    {
        return dataInizio;
    }

    public int getDataFine()
    {
        return dataFine;
    }

    public Camera getCamera()
    {
        return camera;
    }

    public boolean isInCorso()
    {
        return inCorso;
    }

    public void addCliente(Cliente c)
    {
        clienti.add(c);
    }

    public List<Cliente> getClienti()
    {
        return clienti;
    }

    public ContoFinale getConto()
    {
        return conto;
    }

    public List<Spesa> getSpese()
    {
        return spese;
    }

    public void setConto(ContoFinale c)
    {
        conto = c;
    }


}
