//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Spesa.java
//  @ Date : 15/06/2010
//  @ Author : michrag
//
//

package dominio;

import java.util.*;




public class Spesa
{
    private int data;
    private double importo;
    private Soggiorno soggiorno;
    public ContoFinale Unnamed2;

    public Spesa(double euro)
    {
        super();
        this.importo = euro;
    }

    public double getImporto()
    {
        return importo;
    }
}
